version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  nodejs-app:
    build: .
    container_name: nodejs-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  mynetwork:
